# Site settings
title: Tom Jin, Academic Homepage
tag_text: Tom Jin
description: The academic homepage of Tom Jin, PhD student at the Oxford-Warwick Statistics Programme, Department of Statistics, University of Warwick.

# Build settings
markdown: kramdown

exclude: ["README.md"]
